[build]
  publish = "."
  command = ""

[[headers]]
  for = "/api/*"
  [headers.values]
    Content-Type = "application/json"
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"